package com.istloja.vistas;

import com.istdloja.modelo.Inventario;
import com.istdloja.modelo.Persona;
import com.istdloja.modelo.Provedores;
import com.istloja.controlador.Inventariobd;
import com.istloja.controlador.Personabd;
import com.istloja.controlador.Provedoresbd;
import com.istloja.modelTables.ModelTablePersona;
import com.istloja.utilidad.Utilidades;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import com.istloja.modelTables.ComunicacionvistaModelosTablas;
import com.istloja.modelTables.ModelTableInventario;
import com.istloja.modelTables.ModelTableProvedores;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author danielmora
 */
public class GestionContable extends javax.swing.JFrame implements ComunicacionvistaModelosTablas {

    private Utilidades utilidades;
    private Personabd controladorPersona;
    private Provedoresbd controladorprovedor;
    private Inventariobd controladorinvetario;
    private Persona personaEditar;
    private Inventario inventarioEditarSeleccionado;
    private GestionPersona gestionPersona;
    private ModelTablePersona modelTablePersona;
    private ModelTableProvedores modelTableProvedores;
    private ModelTableInventario modelTableInventario;

    /**
     * Creates new form GestionPersona2
     */
    public GestionContable() {

        controladorPersona = new Personabd();
        controladorprovedor = new Provedoresbd();
        controladorinvetario = new Inventariobd();
        modelTablePersona = new ModelTablePersona(controladorPersona.obtenerPersona(), this);
        modelTableProvedores = new ModelTableProvedores(controladorprovedor.obtenerProvedores(), this);
        modelTableInventario = new ModelTableInventario(controladorinvetario.obtenerInventario(), this);
        initComponents();
        utilidades = new Utilidades();
        gestionPersona = new GestionPersona(txtCedula, txtNombre, txtApellido, txtDireccion, txtTelefono, txtCorreo, utilidades, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tabGeneral = new javax.swing.JTabbedPane();
        panelClientes = new javax.swing.JPanel();
        BotonBuscarTelefono = new javax.swing.JButton();
        panelCuerpoRegistro = new javax.swing.JPanel();
        jLabelCedula = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonTraer = new javax.swing.JButton();
        botonLimpiarCajas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BotonBuscarCedula = new javax.swing.JButton();
        jScrollCliente = new javax.swing.JScrollPane();
        TablaCliente = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        comboParametroBusquedaPersona = new javax.swing.JComboBox<>();
        txtParametroBusquedaPersona = new javax.swing.JTextField();
        btnBuscarPersona = new javax.swing.JButton();
        panelProvedores = new javax.swing.JPanel();
        titulo_provedores = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtxRuc = new javax.swing.JTextField();
        txtxRazonSiocial = new javax.swing.JTextField();
        txtTipo_actividad = new javax.swing.JTextField();
        txtNombre_Representante_Legal = new javax.swing.JTextField();
        txtApellido_Representante_legal = new javax.swing.JTextField();
        txtTelefono_Provedores = new javax.swing.JTextField();
        btnGuardarProvedores = new javax.swing.JButton();
        txtCorreo_provedores = new javax.swing.JTextField();
        btnEditarProvedores = new javax.swing.JButton();
        btnEliminarProvedores = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        conmboParametroBusquedaProvedor = new javax.swing.JComboBox<>();
        txtPramatroBusquedaProvedor = new javax.swing.JTextField();
        btnBuscarProvedor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProvedores = new javax.swing.JTable();
        panelInventario = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtcodigoProductoInvntario = new javax.swing.JTextField();
        txtdescripcionInventario = new javax.swing.JTextField();
        txtprecioCompraInvntario = new javax.swing.JTextField();
        txtprecioVentaInventario = new javax.swing.JTextField();
        txtcatidadInventario = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnguardarInventario = new javax.swing.JButton();
        btneditarInventario = new javax.swing.JButton();
        btneliminarInventario = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        combo_busqueda_INVENTARIO = new javax.swing.JComboBox<>();
        txtParamtroBusquedaInventario = new javax.swing.JTextField();
        btnBuscarComboboxInventario = new javax.swing.JButton();
        titulo_inventario = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableInventario = new javax.swing.JTable();
        panelVenta = new javax.swing.JPanel();
        titulo_venta = new javax.swing.JLabel();
        Menu_general = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        subMenuBuscarPersona = new javax.swing.JMenuItem();
        subMenuGuardar = new javax.swing.JMenuItem();
        subMenuEditar = new javax.swing.JMenuItem();
        subMenuEliminar = new javax.swing.JMenuItem();
        subMenuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jLabel4.setText("jLabel4");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu5.setText("jMenu5");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Persona");

        BotonBuscarTelefono.setText("Buscar");
        BotonBuscarTelefono.setToolTipText("Buscar Usuario Por un Telefono");
        BotonBuscarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarTelefonoActionPerformed(evt);
            }
        });

        jLabelCedula.setText("Cedula");

        jLabelNombre.setText("Nombre");

        jLabelApellido.setText("Apellido");

        jLabelDireccion.setText("Direccion");

        jLabelTelefono.setText("Telefono");

        jLabelCorreo.setText("Correo");

        botonGuardar.setText("GUARDAR");
        botonGuardar.setToolTipText("Guardamos un Usuario");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonEditar.setText("EDITAR");
        botonEditar.setToolTipText("Editamos un Usuario");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonEliminar.setText("ELIMINAR");
        botonEliminar.setToolTipText("Eliminamos un Usuario");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonTraer.setText("TRAER");
        botonTraer.setToolTipText("Mostramos el ultimo Usuario Ingresado");
        botonTraer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTraerActionPerformed(evt);
            }
        });

        botonLimpiarCajas.setText("Limpiar");
        botonLimpiarCajas.setToolTipText("Limpiamos las cajas de texto y se inician en vacio");
        botonLimpiarCajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarCajasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCuerpoRegistroLayout = new javax.swing.GroupLayout(panelCuerpoRegistro);
        panelCuerpoRegistro.setLayout(panelCuerpoRegistroLayout);
        panelCuerpoRegistroLayout.setHorizontalGroup(
            panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoRegistroLayout.createSequentialGroup()
                .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCuerpoRegistroLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDireccion)
                            .addGroup(panelCuerpoRegistroLayout.createSequentialGroup()
                                .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jLabelCedula)
                                    .addComponent(jLabelTelefono)
                                    .addComponent(jLabelCorreo))
                                .addGap(5, 5, 5))
                            .addComponent(jLabelApellido, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(221, 221, 221)
                        .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCedula, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefono)
                            .addComponent(txtDireccion)
                            .addComponent(txtCorreo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuerpoRegistroLayout.createSequentialGroup()
                        .addContainerGap(166, Short.MAX_VALUE)
                        .addComponent(botonGuardar)
                        .addGap(33, 33, 33)
                        .addComponent(botonEditar)
                        .addGap(40, 40, 40)
                        .addComponent(botonEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(botonTraer)
                        .addGap(28, 28, 28)
                        .addComponent(botonLimpiarCajas)))
                .addContainerGap())
        );
        panelCuerpoRegistroLayout.setVerticalGroup(
            panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoRegistroLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonEditar)
                    .addComponent(botonEliminar)
                    .addComponent(botonTraer)
                    .addComponent(botonLimpiarCajas)))
        );

        jLabel1.setText("Registro Persona");

        BotonBuscarCedula.setText("Buscar");
        BotonBuscarCedula.setToolTipText("Buscar Usuario Por una Cedula");
        BotonBuscarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarCedulaActionPerformed(evt);
            }
        });

        TablaCliente.setModel(modelTablePersona);
        jScrollCliente.setViewportView(TablaCliente);

        jLabel2.setText("Buscar Cliente");

        comboParametroBusquedaPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula", "Nombre", "Apellido", "Correo" }));
        comboParametroBusquedaPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboParametroBusquedaPersonaActionPerformed(evt);
            }
        });

        btnBuscarPersona.setText("Buscar");
        btnBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientesLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 493, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(161, 161, 161))
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addComponent(panelCuerpoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonBuscarCedula)
                    .addComponent(BotonBuscarTelefono, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(130, 130, 130))
            .addComponent(jScrollCliente, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(comboParametroBusquedaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtParametroBusquedaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnBuscarPersona)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(BotonBuscarCedula)
                        .addGap(125, 125, 125)
                        .addComponent(BotonBuscarTelefono))
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelCuerpoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboParametroBusquedaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtParametroBusquedaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPersona))
                .addGap(18, 18, 18)
                .addComponent(jScrollCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabGeneral.addTab("Clientes ", panelClientes);

        titulo_provedores.setText("Registro Provedores");
        titulo_provedores.setMaximumSize(new java.awt.Dimension(125, 26));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Proveedores "));

        jLabel3.setText("Ruc");

        jLabel5.setText("Razon Social");

        jLabel6.setText("Tipo Actividad");

        jLabel7.setText("Nombre_Representante_legal");

        jLabel8.setText("Apellido_Representante_legal");

        jLabel9.setText("Telefono");

        jLabel10.setText("Correo");

        btnGuardarProvedores.setText("GUARDAR");
        btnGuardarProvedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProvedoresActionPerformed(evt);
            }
        });

        btnEditarProvedores.setText("EDITAR");

        btnEliminarProvedores.setText("ELIMINAR");

        jLabel11.setText("Buscar");

        conmboParametroBusquedaProvedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBuscarProvedor.setText("Buscar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(btnGuardarProvedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditarProvedores)
                .addGap(134, 134, 134)
                .addComponent(btnEliminarProvedores)
                .addGap(84, 84, 84))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtxRuc)
                    .addComponent(txtxRazonSiocial)
                    .addComponent(txtTipo_actividad)
                    .addComponent(txtNombre_Representante_Legal)
                    .addComponent(txtApellido_Representante_legal)
                    .addComponent(txtTelefono_Provedores)
                    .addComponent(txtCorreo_provedores, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel11)
                        .addGap(45, 45, 45)
                        .addComponent(conmboParametroBusquedaProvedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(txtPramatroBusquedaProvedor, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(btnBuscarProvedor)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtxRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtxRazonSiocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTipo_actividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNombre_Representante_Legal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtApellido_Representante_legal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTelefono_Provedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCorreo_provedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminarProvedores)
                        .addComponent(btnEditarProvedores))
                    .addComponent(btnGuardarProvedores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(conmboParametroBusquedaProvedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPramatroBusquedaProvedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProvedor))
                .addContainerGap())
        );

        tablaProvedores.setModel(modelTableProvedores);
        jScrollPane2.setViewportView(tablaProvedores);

        javax.swing.GroupLayout panelProvedoresLayout = new javax.swing.GroupLayout(panelProvedores);
        panelProvedores.setLayout(panelProvedoresLayout);
        panelProvedoresLayout.setHorizontalGroup(
            panelProvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProvedoresLayout.createSequentialGroup()
                .addGroup(panelProvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProvedoresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelProvedoresLayout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(titulo_provedores, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        panelProvedoresLayout.setVerticalGroup(
            panelProvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProvedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo_provedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabGeneral.addTab("Provedores", panelProvedores);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Inventario"));

        jLabel12.setText("CODIGO PRODUCTO");

        jLabel13.setText("DESCRIPCION");

        jLabel14.setText("PRECIO COMPRA");

        jLabel15.setText("PRECION VENTA");

        jLabel17.setText("CANTIDAD");

        btnguardarInventario.setText("GUARDAR");
        btnguardarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarInventarioActionPerformed(evt);
            }
        });

        btneditarInventario.setText("EDITAR");
        btneditarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarInventarioActionPerformed(evt);
            }
        });

        btneliminarInventario.setText("ELIMINAR");
        btneliminarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarInventarioActionPerformed(evt);
            }
        });

        jLabel18.setText("BUSQUEDA");

        combo_busqueda_INVENTARIO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buscar Codigo", "Buscar Descripcion" }));

        btnBuscarComboboxInventario.setText("BUSCAR");
        btnBuscarComboboxInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarComboboxInventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtcodigoProductoInvntario)
                                    .addComponent(txtdescripcionInventario)
                                    .addComponent(txtprecioCompraInvntario)
                                    .addComponent(txtprecioVentaInventario)
                                    .addComponent(txtcatidadInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnguardarInventario)
                                .addGap(139, 139, 139)
                                .addComponent(btneditarInventario)
                                .addGap(113, 113, 113)
                                .addComponent(btneliminarInventario))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel18)
                        .addGap(57, 57, 57)
                        .addComponent(combo_busqueda_INVENTARIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(txtParamtroBusquedaInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarComboboxInventario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtcodigoProductoInvntario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel13)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdescripcionInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtprecioCompraInvntario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtprecioVentaInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtcatidadInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardarInventario)
                    .addComponent(btneditarInventario)
                    .addComponent(btneliminarInventario))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(combo_busqueda_INVENTARIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtParamtroBusquedaInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarComboboxInventario))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        titulo_inventario.setText("Registro Inventario");

        tableInventario.setModel(modelTableInventario);
        jScrollPane3.setViewportView(tableInventario);

        javax.swing.GroupLayout panelInventarioLayout = new javax.swing.GroupLayout(panelInventario);
        panelInventario.setLayout(panelInventarioLayout);
        panelInventarioLayout.setHorizontalGroup(
            panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInventarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo_inventario)
                .addGap(435, 435, 435))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        panelInventarioLayout.setVerticalGroup(
            panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInventarioLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titulo_inventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        tabGeneral.addTab("Inventario", panelInventario);

        titulo_venta.setText("Registro Venta");

        javax.swing.GroupLayout panelVentaLayout = new javax.swing.GroupLayout(panelVenta);
        panelVenta.setLayout(panelVentaLayout);
        panelVentaLayout.setHorizontalGroup(
            panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVentaLayout.createSequentialGroup()
                .addContainerGap(872, Short.MAX_VALUE)
                .addComponent(titulo_venta)
                .addGap(74, 74, 74))
        );
        panelVentaLayout.setVerticalGroup(
            panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo_venta)
                .addContainerGap(874, Short.MAX_VALUE))
        );

        tabGeneral.addTab("Venta", panelVenta);

        Menu_general.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menuArchivo.setText("Archivo");

        jMenu6.setText("Acciones Persona");

        subMenuBuscarPersona.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        subMenuBuscarPersona.setText("Buscar ");
        subMenuBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuBuscarPersonaActionPerformed(evt);
            }
        });
        jMenu6.add(subMenuBuscarPersona);

        subMenuGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        subMenuGuardar.setText("Guardar");
        subMenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuGuardarActionPerformed(evt);
            }
        });
        jMenu6.add(subMenuGuardar);

        subMenuEditar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        subMenuEditar.setText("Editar");
        subMenuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuEditarActionPerformed(evt);
            }
        });
        jMenu6.add(subMenuEditar);

        subMenuEliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, java.awt.event.InputEvent.CTRL_MASK));
        subMenuEliminar.setText("Eliminar");
        subMenuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuEliminarActionPerformed(evt);
            }
        });
        jMenu6.add(subMenuEliminar);

        menuArchivo.add(jMenu6);

        subMenuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        subMenuSalir.setText("Salir");
        subMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(subMenuSalir);

        Menu_general.add(menuArchivo);

        jMenu2.setText("Editar");
        Menu_general.add(jMenu2);

        jMenu4.setText("Acerca de");
        Menu_general.add(jMenu4);

        setJMenuBar(Menu_general);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabGeneral)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabGeneral)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

// Funcionalidad es del Boton en un metodo para reutilizar Codigo
    public void botonguardarPersona() {
        if (controladorPersona.getPersonaCedula(txtCedula.getText()) != null) {
            JOptionPane.showMessageDialog(rootPane, "La Persona con ese numero de cedula ya se encuentra en el Sistema", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Persona personaGuardar = gestionPersona.guardarEditar();

            if (personaGuardar != null) {
                if (controladorPersona.crearPersona(personaGuardar)) {
                    JOptionPane.showMessageDialog(rootPane, "Persona Registrada Corectamente en el sistema.");
                    gestionPersona.vaciarCajasPersona();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error al registrar Persona");
                }
                //persona.mostrarResultado();
            }

        }

    }

    public void botonEditarPersona() {

            if (personaEditar == null) { // validamos que exista una persona para Editar 
                JOptionPane.showMessageDialog(rootPane, "No hay una persona seleccionada para Editar !", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Persona personaEditarLocal = gestionPersona.guardarEditar();
            if (personaEditarLocal != null) {// Comprobamos que la persona este corectamente valiadada los campos
                personaEditarLocal.setIdPersona(personaEditar.getIdPersona());
                if (controladorPersona.modificarPersona(personaEditarLocal)) { // Sila perona se edito corectamente
                    JOptionPane.showMessageDialog(rootPane, "Persona editada con exito en el Sitema");
                    gestionPersona.vaciarCajasPersona();
                    personaEditar = null; // Dejamos la persona en vacio si se desea busca se tendra que ingresar una nueva Persona
                } else {
                    JOptionPane.showMessageDialog(rootPane, "No se pudo Editar la Persona !", "Error", JOptionPane.ERROR_MESSAGE);
                }

            }

    }

    public void buscarPersonaporCedula() {

        Persona persona = controladorPersona.getPersonaCedula(txtCedula.getText());

        if (persona != null) {
            txtCedula.setText(persona.getCedula());
            txtNombre.setText(persona.getNombre());
            txtApellido.setText(persona.getApellido());
            txtDireccion.setText(persona.getDireccion());
            txtTelefono.setText(persona.getTelefono());
            txtCorreo.setText(persona.getCorreo());
            personaEditar = persona;

        } else {
            JOptionPane.showMessageDialog(rootPane, "Persona no encontrada en el sistema", "Error", JOptionPane.ERROR_MESSAGE);
            txtCedula.setText(null);
            txtCedula.requestFocus();
        }

    }

    public void botonEliminarPersona() {// Funcionalidad del Boton Eliminar 
        if (personaEditar != null) {
            if (controladorPersona.eliminarPersona(personaEditar)) {
                JOptionPane.showMessageDialog(rootPane, "Persona Eliminada con exito en el Sitema");
                gestionPersona.vaciarCajasPersona();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se Puedo eliminar la Persona seleccionada", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "No Existe persona para Editar", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }
    private void subMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_subMenuSalirActionPerformed

    private void subMenuBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuBuscarPersonaActionPerformed
        buscarPersonaporCedula();
    }//GEN-LAST:event_subMenuBuscarPersonaActionPerformed

    private void subMenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuGuardarActionPerformed
        botonguardarPersona();
    }//GEN-LAST:event_subMenuGuardarActionPerformed

    private void subMenuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuEditarActionPerformed
        botonEditarPersona();
    }//GEN-LAST:event_subMenuEditarActionPerformed

    private void subMenuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subMenuEliminarActionPerformed

    private void botonLimpiarCajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarCajasActionPerformed
        gestionPersona.vaciarCajasPersona();
    }//GEN-LAST:event_botonLimpiarCajasActionPerformed

    private void BotonBuscarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarCedulaActionPerformed
        buscarPersonaporCedula();
    }//GEN-LAST:event_BotonBuscarCedulaActionPerformed

    private void botonTraerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTraerActionPerformed
        List<Persona> listapersona = controladorPersona.obtenerPersona(); // me retona una lista de personas
        personaEditar = listapersona.get(listapersona.size() - 1); // Obtengo la ultima persona de mi arreglo pongo -1 porque sixw cominexa desde 1 y el indice es desde 0

        txtCedula.setText(personaEditar.getCedula());   // Mostramos el cada casilla el dato de la persona
        txtNombre.setText(personaEditar.getNombre());
        txtApellido.setText(personaEditar.getApellido());
        txtDireccion.setText(personaEditar.getDireccion());
        txtTelefono.setText(personaEditar.getTelefono());
        txtCorreo.setText(personaEditar.getCorreo());

    }//GEN-LAST:event_botonTraerActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        botonEliminarPersona();
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed

        botonEditarPersona();
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed

        botonguardarPersona();
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void BotonBuscarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarTelefonoActionPerformed
        Persona persona = controladorPersona.getPersonaTelefono(txtTelefono.getText());
        if (persona != null) {
            txtCedula.setText(persona.getCedula());
            txtNombre.setText(persona.getNombre());
            txtApellido.setText(persona.getApellido());
            txtDireccion.setText(persona.getDireccion());
            txtTelefono.setText(persona.getTelefono());
            txtCorreo.setText(persona.getCorreo());
            personaEditar = persona;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Persona no encontrada en el sistema", "Error", JOptionPane.ERROR_MESSAGE);
            txtTelefono.setText(null);
            txtTelefono.requestFocus();
        }
    }//GEN-LAST:event_BotonBuscarTelefonoActionPerformed

    private void btnBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPersonaActionPerformed
//        controladorPersona.getPersonaCedula(txtParametroBusquedaPersona.getText());
//        List<Persona> personas = new ArrayList<>();
//        personas.add(controladorPersona.getPersonaCedula(txtParametroBusquedaPersona.getText()));
//        modelTablePersona.setPersonas(personas);
//        modelTablePersona.fireTableDataChanged();
////        List<Persona> personaNombre = controladorPersona.getPersonaNombre(txtParametroBusquedaPersona.getText());
////        modelTablePersona.setPersonas(personaNombre);
////        modelTablePersona.fireTableDataChanged();

        if (comboParametroBusquedaPersona.getSelectedItem().equals("Cedula")) {
            List<Persona> personas = new ArrayList<>();
            personas.add(controladorPersona.getPersonaCedula(txtParametroBusquedaPersona.getText()));
            modelTablePersona.setPersonas(personas);
            modelTablePersona.fireTableDataChanged();
            
        }else{
         //JOptionPane.showMessageDialog(null,"no se encontro");
        }
        if (comboParametroBusquedaPersona.getSelectedItem().equals("Nombre")) {
            List<Persona> personaNombre = controladorPersona.getPersonaNombre(txtParametroBusquedaPersona.getText());
            modelTablePersona.setPersonas(personaNombre);
            modelTablePersona.fireTableDataChanged();
            txtParametroBusquedaPersona.setText(null);
        }else{
         //JOptionPane.showMessageDialog(null,"no se encontro");
        }
        
        if (comboParametroBusquedaPersona.getSelectedItem().equals("Apellido")) {
            List<Persona> personaNombre = controladorPersona.getPersonaApellido(txtParametroBusquedaPersona.getText());
            modelTablePersona.setPersonas(personaNombre);
            modelTablePersona.fireTableDataChanged();
            txtParametroBusquedaPersona.setText(null);
        }else{
         //JOptionPane.showMessageDialog(null,"no se encontro");
        }
        if (comboParametroBusquedaPersona.getSelectedItem().equals("Correo")) {
            List<Persona> personaNombre = controladorPersona.getPersonaCorreo(txtParametroBusquedaPersona.getText());
            modelTablePersona.setPersonas(personaNombre);
            modelTablePersona.fireTableDataChanged();
            txtParametroBusquedaPersona.setText(null);
        }else{
         //JOptionPane.showMessageDialog(null,"no se encontro");
        }


    }//GEN-LAST:event_btnBuscarPersonaActionPerformed

    private void comboParametroBusquedaPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboParametroBusquedaPersonaActionPerformed

    }//GEN-LAST:event_comboParametroBusquedaPersonaActionPerformed

    private void btnGuardarProvedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProvedoresActionPerformed
        Provedores provedores = new Provedores();
        provedores.setRuc(txtxRuc.getText());
        provedores.setRazonSocial(txtxRazonSiocial.getText());
        provedores.setTipoActividad(txtTipo_actividad.getText());
        provedores.setNombreRepresentanteLegal(txtNombre_Representante_Legal.getText());
        provedores.setApellidoRepresentanteLegal(txtApellido_Representante_legal.getText());
        provedores.setTelefono(txtTelefono_Provedores.getText());
        provedores.setCorreo(txtCorreo_provedores.getText());
        if (controladorprovedor.registrarProvedores(provedores)) {
            JOptionPane.showMessageDialog(null,"Se Gegistro Correctamente el Provedor");
            vaciarProvedores();
             modelTableProvedores.setProvedores(controladorprovedor.obtenerProvedores());
             modelTableProvedores.fireTableDataChanged();
            
        }else{
        
            JOptionPane.showMessageDialog(rootPane, "No se pudo Guardar la Provedor !", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnGuardarProvedoresActionPerformed

    private void btnguardarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarInventarioActionPerformed
          Inventario inventario = new Inventario();
        inventario.setCodigo_pro(txtcodigoProductoInvntario.getText());
        inventario.setDescripcion(txtdescripcionInventario.getText());
        inventario.setPrecio_compra(txtprecioCompraInvntario.getText());
        inventario.setPrecio_venta(txtprecioVentaInventario.getText());
        inventario.setCan_productos(txtcatidadInventario.getText());
        
        if (utilidades.validarInventario(txtcodigoProductoInvntario.getText())) {
             controladorinvetario.insertarProducto(inventario); 
             JOptionPane.showMessageDialog(null,"Se Gegistro Correctamente el Producto");
             vaciarInventario();
              modelTableInventario.setInventarios(controladorinvetario.obtenerInventario());
              modelTableInventario.fireTableDataChanged();
        }else {
            JOptionPane.showMessageDialog(rootPane, "No se pudo Guardar la Inventario el Codigo Solo Numeros!", "Error", JOptionPane.ERROR_MESSAGE);
        }
//        if (controladorinvetario.insertarProducto(inventario)) {
//            JOptionPane.showMessageDialog(null,"Se Gegistro Correctamente el Producto");
//            vaciarProvedores();
//            
//            
//        }else{
//        
//            JOptionPane.showMessageDialog(rootPane, "No se pudo Guardar la Provedor !", "Error", JOptionPane.ERROR_MESSAGE);
//        }
    }//GEN-LAST:event_btnguardarInventarioActionPerformed

    private void btneditarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarInventarioActionPerformed
        if (inventarioEditarSeleccionado == null) { // validamos que exista una persona para Editar 
            JOptionPane.showMessageDialog(rootPane, "No hay una Producto seleccionada para Editar !", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (inventarioEditarSeleccionado != null) {// Comprobamos que la persona este corectamente valiadada los campos
            inventarioEditarSeleccionado = valoresActualizadosInventario(inventarioEditarSeleccionado);
            if (controladorinvetario.actualizarInventario(inventarioEditarSeleccionado)){ // Sila perona se edito corectamente
                JOptionPane.showMessageDialog(rootPane, "Producto editado con exito en el Sitema");
                vaciarInventario();
             inventarioEditarSeleccionado=null;
              modelTableInventario.setInventarios(controladorinvetario.obtenerInventario());
             modelTableInventario.fireTableDataChanged();
            
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se pudo Editar el Producto !", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btneditarInventarioActionPerformed

    private Inventario valoresActualizadosInventario(Inventario inventario){
        inventario.setCodigo_pro(txtcodigoProductoInvntario.getText());
        inventario.setDescripcion(txtdescripcionInventario.getText());
        inventario.setPrecio_compra(txtprecioCompraInvntario.getText());
        inventario.setPrecio_venta(txtprecioVentaInventario.getText());
        inventario.setCan_productos(txtcatidadInventario.getText());
        return inventario;
    }
    
    
    private void btneliminarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarInventarioActionPerformed
        if (inventarioEditarSeleccionado != null) {
            if (controladorinvetario.eliminarInventario(inventarioEditarSeleccionado)) {
                JOptionPane.showMessageDialog(rootPane, "Producto Eliminado con exito en el Sitema");
               vaciarInventario();
               modelTableInventario.setInventarios(controladorinvetario.obtenerInventario());
              modelTableInventario.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se Puedo eliminar El Producto seleccionada", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "No Existe Producto para Eliminar", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btneliminarInventarioActionPerformed

    private void btnBuscarComboboxInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarComboboxInventarioActionPerformed

//        System.out.println(combo_busqueda_INVENTARIO.getSelectedIndex());
        switch (combo_busqueda_INVENTARIO.getSelectedIndex()) {
            case 0://Codigo     
                modelTableInventario.setInventarios(controladorinvetario.obetenerProdctoInventarioCodgo(txtParamtroBusquedaInventario.getText()));
              modelTableInventario.fireTableDataChanged();
                
                break;
            case 1://Descripcion
                 modelTableInventario.setInventarios(controladorinvetario.obetenerProdctoInventarioDescripcion(txtParamtroBusquedaInventario.getText()));
              modelTableInventario.fireTableDataChanged();
                break;
            default:
                
        }
    }//GEN-LAST:event_btnBuscarComboboxInventarioActionPerformed

    void vaciarProvedores(){
        txtxRuc.setText("");
        txtxRazonSiocial.setText("");
        txtTipo_actividad.setText("");
        txtNombre_Representante_Legal.setText("");
        txtApellido_Representante_legal.setText("");
        txtTelefono_Provedores.setText("");
        txtCorreo_provedores.setText("");
    }
    void vaciarInventario(){
       txtcodigoProductoInvntario.setText("");
        txtdescripcionInventario.setText("");
        txtprecioCompraInvntario.setText("");
        txtprecioVentaInventario.setText("");
       txtcatidadInventario.setText("");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionContable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscarCedula;
    private javax.swing.JButton BotonBuscarTelefono;
    private javax.swing.JMenuBar Menu_general;
    private javax.swing.JTable TablaCliente;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonLimpiarCajas;
    private javax.swing.JButton botonTraer;
    private javax.swing.JButton btnBuscarComboboxInventario;
    private javax.swing.JButton btnBuscarPersona;
    private javax.swing.JButton btnBuscarProvedor;
    private javax.swing.JButton btnEditarProvedores;
    private javax.swing.JButton btnEliminarProvedores;
    private javax.swing.JButton btnGuardarProvedores;
    private javax.swing.JButton btneditarInventario;
    private javax.swing.JButton btneliminarInventario;
    private javax.swing.JButton btnguardarInventario;
    private javax.swing.JComboBox<String> comboParametroBusquedaPersona;
    private javax.swing.JComboBox<String> combo_busqueda_INVENTARIO;
    private javax.swing.JComboBox<String> conmboParametroBusquedaProvedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelCuerpoRegistro;
    private javax.swing.JPanel panelInventario;
    private javax.swing.JPanel panelProvedores;
    private javax.swing.JPanel panelVenta;
    private javax.swing.JMenuItem subMenuBuscarPersona;
    private javax.swing.JMenuItem subMenuEditar;
    private javax.swing.JMenuItem subMenuEliminar;
    private javax.swing.JMenuItem subMenuGuardar;
    private javax.swing.JMenuItem subMenuSalir;
    private javax.swing.JTabbedPane tabGeneral;
    private javax.swing.JTable tablaProvedores;
    private javax.swing.JTable tableInventario;
    private javax.swing.JLabel titulo_inventario;
    private javax.swing.JLabel titulo_provedores;
    private javax.swing.JLabel titulo_venta;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellido_Representante_legal;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCorreo_provedores;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre_Representante_Legal;
    private javax.swing.JTextField txtParametroBusquedaPersona;
    private javax.swing.JTextField txtParamtroBusquedaInventario;
    private javax.swing.JTextField txtPramatroBusquedaProvedor;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono_Provedores;
    private javax.swing.JTextField txtTipo_actividad;
    private javax.swing.JTextField txtcatidadInventario;
    private javax.swing.JTextField txtcodigoProductoInvntario;
    private javax.swing.JTextField txtdescripcionInventario;
    private javax.swing.JTextField txtprecioCompraInvntario;
    private javax.swing.JTextField txtprecioVentaInventario;
    private javax.swing.JTextField txtxRazonSiocial;
    private javax.swing.JTextField txtxRuc;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clickPersona(Persona p) { // seteamos los valores y se muestran los datos en el folmulario
        System.out.println("Persona" + p.toString());
        txtCedula.setText(p.getCedula());
        txtNombre.setText(p.getNombre());
        txtApellido.setText(p.getApellido());
        txtDireccion.setText(p.getDireccion());
        txtTelefono.setText(p.getTelefono());
        txtCorreo.setText(p.getCorreo());
    }

    @Override
    public void clickProveedores(Provedores provedores) {
         txtxRuc.setText(provedores.getRuc());
        txtxRazonSiocial.setText(provedores.getRazonSocial());
        txtTipo_actividad.setText(provedores.getTipoActividad());
        txtNombre_Representante_Legal.setText(provedores.getNombreRepresentanteLegal());
        txtApellido_Representante_legal.setText(provedores.getApellidoRepresentanteLegal());
        txtTelefono_Provedores.setText(provedores.getTelefono());
        txtCorreo_provedores.setText(provedores.getCorreo());
    }

    @Override
    public void clickInventario(Inventario inventario) {
        inventarioEditarSeleccionado = inventario;
        txtcodigoProductoInvntario.setText(inventario.getCodigo_pro());
        txtdescripcionInventario.setText(inventario.getDescripcion());
        txtprecioCompraInvntario.setText(inventario.getPrecio_compra());
        txtprecioVentaInventario.setText(inventario.getPrecio_venta());
       txtcatidadInventario.setText(inventario.getCan_productos());
    }
}
